# Ckip builds for pushed tags (as commit will already have been built).
if: tag IS blank

# Only build on the following base branches.
branches:
  only:
    - master
    - develop

# Use Node.js in the container.
language: node_js

# Specifically use Node.js v10.
node_js:
  - '10'

# Setup caching for yarn dependencies (speeds up builds).
cache: yarn

# Setup the build before tests are ran.
install:
  - yarn install

# Run the build (only tests in this case).
script:
  - npm run test

# Commands to run before deploying.
before_deploy:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp/awscli-bundle.zip"
  - unzip /tmp/awscli-bundle.zip -d /tmp
  - /tmp/awscli-bundle/install -b $HOME/bin/aws
  - export PATH=$PATH:$HOME/bin

# Run the deploy script.
deploy:
  - provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
